package com.wacoco.searchFunctionality;

import java.util.Map;

public class FilterConfig {
    public static final Map<String, String> COUNTRIES_MAP = Map.ofEntries(
            Map.entry("United States", "US"),
            Map.entry("China", "CN"),
            Map.entry("European Patents", "EP"),
            Map.entry("WO - WIPO", "WO"),
            Map.entry("Japan", "JP"),
            Map.entry("Korea, Republic of", "KR"),
            Map.entry("United Kingdom", "GB"),
            Map.entry("Taiwan", "TW"),
            Map.entry("Canada", "CA"),
            Map.entry("Germany", "DE"),
            Map.entry("Australia", "AU"),
            Map.entry("Spain", "ES"),
            Map.entry("France", "FR"),
            Map.entry("Russia", "RU"),
            Map.entry("Austria", "AT"),
            Map.entry("Poland", "PL"),
            Map.entry("Mexico", "MX"),
            Map.entry("Hong Kong", "HK"),
            Map.entry("Ukraine", "UA"),
            Map.entry("Hungary", "HU"),
            Map.entry("Soviet Union", "SU"),
            Map.entry("Israel", "IL"),
            Map.entry("Malaysia", "MY"),
            Map.entry("South Africa", "ZA"),
            Map.entry("Italy", "IT"),
            Map.entry("India", "IN"),
            Map.entry("Singapore", "SG"),
            Map.entry("Denmark", "DK"),
            Map.entry("Romania", "RO"),
            Map.entry("Philippines", "PH"),
            Map.entry("Netherlands", "NL"),
            Map.entry("Sweden", "SE"),
            Map.entry("Switzerland", "CH"),
            Map.entry("New Zealand", "NZ"),
            Map.entry("Brazil", "BR"),
            Map.entry("Bulgaria", "BG"),
            Map.entry("Greece", "GR"),
            Map.entry("Finland", "FI"),
            Map.entry("Portugal", "PT"),
            Map.entry("Norway", "NO"),
            Map.entry("Czech Republic", "CZ"),
            Map.entry("Ireland", "IE"),
            Map.entry("Slovakia", "SK"),
            Map.entry("Belgium", "BE"),
            Map.entry("Eurasian Patents", "EA"),
            Map.entry("Czechoslovakia", "CS"),
            Map.entry("Slovenia", "SI"),
            Map.entry("Yugoslavia/Serbia and Montenegro", "YU"),
            Map.entry("Luxembourg", "LU"),
            Map.entry("Serbia", "RS"),
            Map.entry("Croatia", "HR"),
            Map.entry("Lithuania", "LT"),
            Map.entry("Latvia", "LV"),
            Map.entry("Moldova", "MD"),
            Map.entry("Saudi Arabia", "SA"),
            Map.entry("Turkey", "TR"),
            Map.entry("Argentina", "AR"),
            Map.entry("ARIPO Patents", "AP"),
            Map.entry("Georgia", "GE"),
            Map.entry("Tunisia", "TN"),
            Map.entry("Jordan", "JO"),
            Map.entry("Egypt", "EG"),
            Map.entry("Indonesia", "ID"),
            Map.entry("Cyprus", "CY"),
            Map.entry("Estonia", "EE"),
            Map.entry("Cuba", "CU"),
            Map.entry("Morocco", "MA"),
            Map.entry("Costa Rica", "CR"),
            Map.entry("German Democratic Republic", "DD"),
            Map.entry("OAPI Patents", "OA"),
            Map.entry("Chile", "CL"),
            Map.entry("Malta", "MT"),
            Map.entry("Zimbabwe", "ZW"),
            Map.entry("Peru", "PE"),
            Map.entry("Colombia", "CO"),
            Map.entry("Iceland", "IS"),
            Map.entry("San Marino", "SM"),
            Map.entry("Algeria", "DZ"),
            Map.entry("Ecuador", "EC"),
            Map.entry("GCC Patents", "GC"),
            Map.entry("Montenegro", "ME"),
            Map.entry("Malawi", "MW"),
            Map.entry("Tajikistan", "TJ"),
            Map.entry("Zambia", "ZM")
    );

    public static final Map<String, String> LEGALSTATUS_MAP = Map.ofEntries(
            Map.entry("Active", "Active"),
            Map.entry("Pending", "Pending"),
            Map.entry("Expired", "Expired"),
            Map.entry("Discontinued", "Discontinued"),
            Map.entry("Inactive", "Inactive"),
            Map.entry("Patented", "Patented"),
            Map.entry("Unknown", "Unknown")
    );
    public static final Map<String, String> DOCTYPE_MAP = Map.ofEntries(
            Map.entry("Patent Application", "PATENT_APPLICATION"),
            Map.entry("Granted Patent", "GRANTED_PATENT"),
            Map.entry("Limited Patent", "LIMITED_PATENT"),
            Map.entry("Unknown", "UNKNOWN"),
            Map.entry("Search Report", "SEARCH_REPORT"),
            Map.entry("Design Right", "DESIGN_RIGHT"),
            Map.entry("Patent of Addition", "PATENT_OF_ADDITION"),
            Map.entry("Abstract", "ABSTRACT"),
            Map.entry("Amended Patent", "AMENDED_PATENT"),
            Map.entry("Amended Application", "AMENDED_APPLICATION"),
            Map.entry("Ambiguous", "AMBIGUOUS"),
            Map.entry("Plant Patent", "PLANT_PATENT"),
            Map.entry("Statutory Invention Register", "STATUTORY_INVENTION_REGISTER"),
            Map.entry("SPC", "SPC")
    );

    public static final Map<String, String> FLAG_MAP = Map.ofEntries(
            Map.entry("Has Title", "&hasTitle="),
            Map.entry("Has Abstract", "&hasAbstract="),
            Map.entry("Has Description", "&hasDescription="),
            Map.entry("Has Full Text", "&hasFullText="),
            Map.entry("Has Granted Patent", "&hasGrantedPatent="),
            Map.entry("Has Grant Event", "&hasGrantEvent="),
            Map.entry("Has National Phase", "&hasNationalPhase="),
            Map.entry("Has Legal Events", "&hasInpadoc="),
            Map.entry("Has DOCDB", "&hasDocdb="),
            Map.entry("Has Applicant", "&hasApplicant="),
            Map.entry("Has Owner", "&hasOwner="),
            Map.entry("Has Inventor", "&hasInventor="),
            Map.entry("Has Agent", "&hasAgent="),
            Map.entry("Has Examiner", "&hasExaminer="),
            Map.entry("Has Sequence Listing", "&hasSequenceListing="),
            Map.entry("Cited By Patent", "&citedByPatent="),
            Map.entry("Cities NPL", "&citiesNpl=")
    );

}
